name: technic_help
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Versi terbaru dari flutter_screenutil yang mendukung null safety
  flutter_screenutil: ^5.0.0
  
  # Ganti scoped_model dengan provider
  provider: ^6.0.0
  
  # Versi terbaru dari rxdart yang kompatibel dengan null safety
  rxdart: ^0.27.0
  
  rect_getter: ^0.0.1
  gradient_text: ^1.0.2
  shared_preferences: ^0.5.2
  http: ^0.12.0+2
  mime: ^0.9.6+2
  image_picker: ^0.8.5+3  # Versi terbaru yang mendukung null safety
  connectivity: ^3.0.6   # Versi terbaru yang mendukung null safety
  url_launcher: ^6.0.12  # Versi terbaru yang mendukung null safety
  fancy_bottom_navigation: ^0.3.2
  cupertino_icons: ^1.0.5 # Versi yang lebih baru dan mendukung null safety

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/illustration.png
    - assets/illustration2.png
    - assets/illustration3.png
    - assets/image_01.png
    - assets/image_02.png
    - assets/logo.png
    - assets/food.jpg
    - assets/background.jpg

  fonts:
    - family: Montserrat-Black
      fonts:
        - asset: assets/Montserrat-Black.ttf

    - family: Montserrat-Medium
      fonts:
        - asset: assets/Montserrat-Medium.ttf

    - family: CustomIcons
      fonts:
        - asset: assets/CustomIcons.ttf

    - family: Poppins-Bold
      fonts:
        - asset: assets/Poppins-Bold.ttf

    - family: Poppins-Medium
      fonts:
        - asset: assets/Poppins-Medium.ttf

    - family: Rubik
      fonts:
        - asset: fonts/Rubik-Regular.ttf
        - asset: fonts/Rubik-Medium.ttf
          weight: 500

    - family: Oswald
      fonts:
        - asset: assets/Oswald-Bold.ttf
          weight: 700
